name: Build and test
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    name: Build and test
    runs-on: macos-11.0
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v1
      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "coinMarketCapKey=1234" >> local.properties
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
  generate-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "coinMarketCapKey=1234" >> local.properties
      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk