name: Jacoco report

on:
  pull_request:
    branches:
      - master

jobs:
  jacoco-report:
    name: Jacoco report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Touch local properties
        run: touch local.properties

      - name: Add Api Key
        run: echo "coinMarketCapKey=1234" >> local.properties

      - name: Run Coverage
        uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            arch: x86
            profile: Nexus 6
            avd-name: test
            emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
            disable-animations: true
            script: ./gradlew connectedCheck
        run: ./gradlew createDebugCoverageReport

      - name: Upload Report
        uses: 'actions/upload-artifact@v2'
        with:
          name: report.xml
          path: app/build/reports/coverage/androidTest/debug/report.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.1
        with:
          path: app/build/reports/coverage/androidTest/debug/report.xml
          token: ${{ secrets.JACOCO_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          debug-mode: false

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"