name: Static Analysis
on:
  pull_request:
    branches:
      - master
jobs:
  ktlint-analysis:
    name: Ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v1
      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "coinMarketCapKey=1234" >> local.properties
      - name: Ktlint Check
        run: ./gradlew ktlintCheck
  detekt-analysis:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v1
      - name: Setup JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Touch local properties
        run: touch local.properties
      - name: Add Api Key
        run: echo "coinMarketCapKey=1234" >> local.properties
      - name: Detekt Check
        run: ./gradlew detekt